"""
CollectBitcoinPrice
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="python_1")
def python_1_func():
    print("teste")

default_args={
    "owner": "Alex Lopes,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-12-01", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Alex Lopes": "mailto:alexlopespereira@gmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cm3webulw15k701npm2uhu77t/cloud-ide/cm460qm2d10xd01mxy5y1tndy/cm460u5p810xo01mxxetixw7e",
    },
)
def CollectBitcoinPrice():
    python_1 = python_1_func()

dag_obj = CollectBitcoinPrice()
