"""
Teste2
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="python_1")
def python_1_func():
    print(3)

default_args={
    "owner": "Associação dos Engenheiros do ITA,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2025-02-06", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Associação dos Engenheiros do ITA": "mailto:aeita.office@gmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cm4d8ikzs00hi01llolal5yk0/cloud-ide/cm6ijl9vf02rd01mdrfq1s1we/cm6smrlfk20i701md4bewlp1x",
    },
)
def Teste2():
    python_1 = python_1_func()

dag_obj = Teste2()
